// <auto-generated />
using BlazorServerCrudDotNet8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerCrudDotNet8.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240426012219_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorServerCrudDotNet8.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Publisher = "CD Projekt",
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 2,
                            Publisher = "FromSoftware",
                            ReleaseYear = 2022,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 3,
                            Publisher = "Nintendo",
                            ReleaseYear = 2022,
                            Title = "The Legend of Zelda: Ocarina of Time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
